CREATE TABLE `operational_checks` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`reference_month` text NOT NULL,
	`period` text NOT NULL,
	`nota_execucao_direta` integer NOT NULL,
	`nota_revisao` integer NOT NULL,
	`nota_direcao_criativa` integer NOT NULL,
	`nota_energia` integer NOT NULL,
	`nota_capacidade` integer NOT NULL,
	`entregas_executadas_gabi` integer,
	`gargalos` text,
	`clientes_pesadas_ids` text,
	`motivos_peso` text,
	`comentario_clientes_pesadas` text,
	`comentario` text,
	`posts_totais` integer,
	`unidades_operacionais` real,
	`carrosseis` integer,
	`reels` integer,
	`estaticos` integer,
	`criativos_trafego` integer,
	`avulsos` integer,
	`copys_devolvidas` integer,
	`designs_refeitos` integer,
	`posts_revisados_gabi` integer,
	`posts_revisados_pedro` integer,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	`updated_at` text DEFAULT (datetime('now')) NOT NULL
);
